### ISSUE TITLE
Error - User with no 'CONNECT' permission.

### ISSUE THREAD

**Issue by nirajdangi4j** [christiandelbianco/monitor-table-change-with-sqltabledependency#28]
Hi,

I am tried to use SqlTableDependency approach. But i am getting this error. 

   at TableDependency.SqlClient.SqlTableDependency`1.CheckIfUserHasPermissions(String connectionString)
   at TableDependency.TableDependency`1..ctor(String connectionString, String tableName, IModelToTableMapper`1 mapper, IUpdateOfModel`1 updateOf, ITableDependencyFilter filter, DmlTriggerType dmlTriggerType, Boolean executeUserPermissionCheck)
   at TableDependency.SqlClient.SqlTableDependency`1..ctor(String connectionString, String tableName, IModelToTableMapper`1 mapper, IUpdateOfModel`1 updateOf, ITableDependencyFilter filter, DmlTriggerType notifyOn, Boolean executeUserPermissionCheck)
   at WindowsFormsApplicationTrack.Form1.Form1_Load(Object sender, EventArgs e) in

Can you help on this.

Thanks,
Niraj

**Comment by nirajdangi4j** [comment]
I have done this. But i am still facing Permission issue. 

It is possible to skip the permissions test done by SqlTableDependency. Set the executeUserPermissionCheck constructor parameter to false. Otherwise an SQL server exception will be thrown if the user does not have sufficient permissions.

**Comment by christiandelbianco** [comment]
Assign to sql login (used in your connection string) 'CONNECT' grant

**Comment by christiandelbianco** [comment]
Or as you wrote, skip the permissions test

**Comment by christiandelbianco** [comment]
In case the user specified in the connection string is not database operator and neither has db_owner role, please make sure to GRANT the following permissions:

    ALTER
    CONNECT
    CONTROL
    CREATE CONTRACT
    CREATE MESSAGE TYPE
    CREATE PROCEDURE
    CREATE QUEUE
    CREATE SERVICE
    EXECUTE
    SELECT
    SUBSCRIBE QUERY NOTIFICATIONS
    VIEW DATABASE STATE
    VIEW DEFINITION

**Comment by nirajdangi4j** [comment]
yes, i can skip the permissions.

**Comment by nirajdangi4j** [comment]
We need to set permissions For database or table?

**Comment by christiandelbianco** [comment]
For DATABASE

**Comment by nirajdangi4j** [comment]
ok.. thanks. i will try and let you know.

**Comment by christiandelbianco** [comment]
if it works simply close the BUG

**Comment by nirajdangi4j** [comment]
I have assigned all permissions to database. But i am still facing same issue.

**Comment by christiandelbianco** [comment]
Have you tried to use DBO ?
