### ISSUE TITLE
Azure 'sys.login_token' is not accessible 

### ISSUE THREAD

**Issue by wpitallo** [christiandelbianco/monitor-table-change-with-sqltabledependency#31]
Hi have you tried this with Azure? When I try I initialize the TableDependency object I get the error below, looks like 'sys.login_token' is not accessible from AzureSQL.

{System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'sys.login_token'.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
at TableDependency.SqlClient.SqlTableDependency`1.CheckIfUserHasPermissions(String connectionString)
at TableDependency.TableDependency`1..ctor(String connectionString, String tableName, IModelToTableMapper`1 mapper, IUpdateOfModel`1 updateOf, ITableDependencyFilter filter, DmlTriggerType dmlTriggerType, Boolean executeUserPermissionCheck)
at Server.Hubs.Challenge.DatabaseSubscriptions

**Comment by christiandelbianco** [comment]
Hi.
Never tried with Azure and also, sqltabledependency does not use this system table: sys.login_token.

**Comment by kivancbakdi** [comment]
Hi @wpitallo,

Sql Service Broker is **not supported** on Microsoft Azure SQL, this may be the reason for this error. You can solve the problem by opening a VM on Azure and manually installing SQL. I keep going like this.

Or browse through alternative services for "Sql Service Broker" on Azure.

**Comment by wpitallo** [comment]
Ok cool thanks very much :)

**Comment by paritoshromy** [comment]
Is this still the case -Sql Service Broker is not supported on Microsoft Azure SQL
