### ISSUE TITLE
Queue containing a message type not expected

### ISSUE THREAD

**Issue by ErikvdBurgwal** [christiandelbianco/monitor-table-change-with-sqltabledependency#33]
Hi,
Every now-and-then I get the following error (in the OnError event). 
Do you either have an idea where this comes from, or a suggestion where I can start debugging?
Thanks,
Erik

Queue containing a message type not expected [http://schemas.microsoft.com/SQL/ServiceBroker/DialogTimer].
Stacktrace:   at TableDependency.Messages.MessagesBag.AddMessage(Message message)
   atTableDependency.SqlClient.SqlTableDependency`1.<>c__DisplayClass63_0.<WaitForNotifications>b__0(Message m)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at TableDependency.SqlClient.SqlTableDependency`1.<WaitForNotifications>d__63.MoveNext()

**Comment by christiandelbianco** [comment]
Which Sql Server DB version are you using?

**Comment by ErikvdBurgwal** [comment]
Hi Christian,
I am using Microsoft SQL Server Developer (64-bit) locally, version 12.0.5207.0 (SQL Server 2014 SP2).
Best regards,
Erik

**Comment by lucusP320** [comment]
Hello,
    I am also receiving this error message.  I am using SQL Server Express 2012 on my local machine.  Is there a solution for this?  Here is the stack trace i received. 

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at TableDependency.SqlClient.SqlTableDependency`1.DropDatabaseObjects(String connectionString, String databaseObjectsNaming)
   at TableDependency.TableDependency`1.Stop()

**Comment by Ashrafnet** [comment]
I'm facing same issue, i'm using sql server developer 2016

**Comment by lucusP320** [comment]
I believe this error is occurring when the computer goes to sleep.  I have an assumption that this is due to it running the SQL Server locally and the local instance of SQL server goes to sleep or becomes idle.  Not exactly sure what the local instance does when the computer goes to sleep.  

I am going to put the database on a production SQL server and see if the problem still continues.  I still see there being an issue though.  If for some reason the server crashes, needs to be taken offline for updates, or possibly even nightly backups occur and my assumption is correct an application could get in a state where it wont be able to access the connection again until it is restarted. 

I will comment again once I move the database and do some further testing.

**Comment by christiandelbianco** [comment]
It is as lucusP320 commented on Mar 12 "**I believe this error is occurring when the computer goes to sleep**".

**Comment by christiandelbianco** [comment]
lucusP320 --> You are very smart!
