### ISSUE TITLE
SqlTransaction problem after some time

### ISSUE THREAD

**Issue by MarcoNegroni** [christiandelbianco/monitor-table-change-with-sqltabledependency#38]
Good morning, we are using SqlTableDependency into an always running Windows Service like a "notifications centralized service"; after about two days of always running we get a sql transaction exception, i logged also the SqlTableDependency status change:

[21:02:33] Status changed: STOPDUETOERROR
[21:02:33] Error message: TableDependency stopped working
exception: System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Rollback()
   at TableDependency.SqlClient.SqlTableDependency`1.<WaitForNotifications>d__63.MoveNext()

Is maybe a sql transaction timeout problem or something like that in the sql server configuration?

Thanks very much in advance

**Comment by christiandelbianco** [comment]
Hi Marco.
One of most frequent reason of problems like your, is due to "pausing" or "sleeping" windows service hosting SqlTableDependency. When this happen, SqlTableDependency connection to DB is disposed and all SqlTableDependency's database objects (TRIGGER, STORED PROCEDURE QUEUE etc...) are removed from DB.

**Comment by MarcoNegroni** [comment]
Thanks very much for your reply, i recompiled the service disabling the "Stop feature" and i logged each status change, i'll let you know.

Thanks

**Comment by christiandelbianco** [comment]
Perfect. Just for your info i have a long test case. SqlTableDependency hosted in a ASP.NET application:

http://sqltabledependency.somee.com/test

Here, SqlTableDependency is running without any stop since a while.

**Comment by MarcoNegroni** [comment]
Good morning, i checked service states but seems always running and during last night is happened again.
What If i enable "ActivateDatabaseLoging"? Which is the log filepath?

Thanks in advance

**Comment by christiandelbianco** [comment]
ActivateDatabaseLoging is use to write logs in the SQL Server log file. Location of this file depends on your database settings.

**Comment by MarcoNegroni** [comment]
I'm checking with the sql server logs, maybe the problem is related to the automatic database backup:

02/20/2018 01:01:17,spid59,Unknown,I/O is frozen on database Notifications. No user action is required. However<c/> if I/O is not resumed promptly<c/> you could cancel the backup.
02/20/2018 01:01:51,spid59,Unknown,I/O was resumed on database Notifications. No user action is required.
02/20/2018 01:01:56,Backup,Unknown,Database backed up. Database: Notifications<c/> creation date(time): 2018/01/17(09:26:14)<c/> pages dumped: 498<c/> first LSN: 380:484:1<c/> last LSN: 381:36:1<c/> number of dump devices: 1<c/> device information: (FILE=1<c/> TYPE=VIRTUAL_DEVICE: {'{70156A24-5C3C-4A82-A418-730FBE367BF1}3'}). This is an informational message only. No user action is required.

**Comment by alexhuang92** [comment]
@MarcoNegroni have you resolved your issue? I am experiencing the same issues and am also checking to see if the database backup is the cause.

**Comment by MarcoNegroni** [comment]
@alexhuang92 no, i decided to stop using TableDependency and i changed the logic by using a direct websocket communication with some memory data.

**Comment by jnallu** [comment]
@MarcoNegroni @alexhuang92 I have the same issue. I am running SQL Table dependency  into a windows service. The server hoisting the service is up and running 24/7. But every now and then the objects are dropped and the service does trigger for data changes As a temp fix,  I wrote a console app that runs every minute, monitor the objects and restart the service if objects are missing.  I am assuming automatic database backup might be the problem. How to solve this?

**Comment by christiandelbianco** [comment]
Does automatic database close or pause active connections?

**Comment by christiandelbianco** [comment]
Removed Transaction from SqlTableDependency

**Comment by jnallu** [comment]
Thanks @christiandelbianco.  So does this fix the issue. Objects being dropped abruptly.

**Comment by sagunpandey** [comment]
@jnallu Can you kindly share us the script that restarts the service if objects are missing? I am facing a similar kind of issue where SqlTableDependency detects change event for a while and then stops working. I am using it in my Web API application, and I have to restart my IIS server to make it work again.

**Comment by fluxium** [comment]
Has anyone attempted to resolve this issue by having your application react to the SqlTableDependency OnError or OnStatusChanged events? I use a wrapper class over SqlTableDependency that has a Configure() method and a Start() method. Start() calls Configure(). The event handler for SqlTableDependency OnError events uses a Polly RetryPolicy to call the Start() method with exponential backoff until it returns without exceptions. I am accessing SQL Server instances over slow/intermittent/noisy links and this design works beautifully for us. The service is resilient without the need for external watch dog servicing.

**Comment by sagunpandey** [comment]
@fluxium I am using an external service that reinitializes SqlTableDependency in a certain interval. This is very inefficient and we are having a lot of issues. Can you kindly share your solution?

**Comment by blarsen06** [comment]
@fluxium Also interested in seeing what you've done.  I've been trying to chain restarts to the OnStatusChanged / OnError events, but it's pretty unreliable.  Are you leveraging this library https://github.com/App-vNext/Polly , and do you happen to have some basic setup, configuration, or samples to follow as it applies to SqlTableDependency?  This is a great project, and I've built way too much around it to abandon it now, but something on the IT side of the house has changed with maintenance overnight, and I'm having to restart this thing daily now.  Thanks in advance.
