### ISSUE TITLE
Nullable types in model class

### ISSUE THREAD

**Issue by georgegeo** [christiandelbianco/monitor-table-change-with-sqltabledependency#53]
hi,
I get this message onError 
Object of type 'System.Int32' cannot be converted to type System.Nullable`1[ .....MY ENUM TYPE...... ]'.

here is the stacktrace:
 at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at TableDependency.EventArgs.RecordChangedEventArgs`1.MaterializeEntity(List`1 messages, IModelToTableMapper`1 mapper)
   at TableDependency.EventArgs.RecordChangedEventArgs`1..ctor(MessagesBag messagesBag, IModelToTableMapper`1 mapper, IEnumerable`1 userInterestedColumns, String server, String database, String sender, CultureInfo cultureInfo)
   at TableDependency.SqlClient.EventArgs.SqlRecordChangedEventArgs`1..ctor(MessagesBag messagesBag, IModelToTableMapper`1 mapper, IEnumerable`1 userInterestedColumns, String server, String database, String sender, CultureInfo cultureInfo)
   at TableDependency.SqlClient.SqlTableDependency`1.GetRecordChangedEventArgs(MessagesBag messagesBag)
   at TableDependency.TableDependency`1.NotifyListenersAboutChange(Delegate[] changeSubscribedList, MessagesBag messagesBag)
   at TableDependency.SqlClient.SqlTableDependency`1.<WaitForNotifications>d__63.MoveNext()

**Comment by christiandelbianco** [comment]
FIXED in 7.0.0.0
