### ISSUE TITLE
SQL Table dependency getting unregistered from application and not receiving further update

### ISSUE THREAD

**Issue by AshishShukla16** [christiandelbianco/monitor-table-change-with-sqltabledependency#61]
Hi Team,

I am using the table dependency in my C# code and it works fine mostly, but it's not reliable because my application is getting unregistered automatically after few time and application does not receive further updates from the registered SQL table. I am using SQL SERVER 2014 version. 
I have subscribed to **OnError** event of SQL Table dependency to log the error.

`SqlTableDependency<Customer> dependency = new SqlTableDependency<Customer>(connectionString, "[dbo].[Customers]");
dependency.OnError += Error;`

Now on the error handler I have just logged the details. I found the once the error handler hits, table dependency stops working.

I do not find the reasons why error handler is getting triggered. This happen some days or even in some weeks, the behavior is not consistent.
Could you please help me to identify the possible causes and scenarios when this may happen.  
Below is the logs

`System.AggregateException: One or more errors occurred. ---> System.Data.SqlClient.SqlException: Invalid object name 'Master.Master_Templates_46328962-9aa7-4e92-b319-9452354068cb'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TableDependency.SqlClient.Extensions.TaskExtensions.<WithCancellation>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TableDependency.SqlClient.SqlTableDependency`1.<WaitForNotifications>d__44.MoveNext()
---> (Inner Exception #0) System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Master.Master_Templates_46328962-9aa7-4e92-b319-9452354068cb'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
ClientConnectionId:44d0142e-dc43-4619-bfb6-9a10759d55d9
Error Number:208,State:12,Class:16<---`

**Comment by christiandelbianco** [comment]
Hi.
Is your sqltabledependency instance hosteb by WINDOWS SERVICE?

**Comment by AshishShukla16** [comment]
Yes it is hosted inside windows service.

**Comment by christiandelbianco** [comment]
Please, check what i wrote on **Requirements** section in home page

**Comment by manhdungitvn** [comment]
When your thread process a task in a long time response, this is will happen
