### ISSUE TITLE
Ignore Properties from model classes

### ISSUE THREAD

**Issue by georgegeo** [christiandelbianco/monitor-table-change-with-sqltabledependency#62]
Is there a way to ignore some properties (those without setter) of classes, so I do not get this error? : 

"Property set method not found."

Stacktrace:

  at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at TableDependency.EventArgs.RecordChangedEventArgs`1.SetValue(Object inputObject, String propertyName, Object propertyVal)
   at TableDependency.EventArgs.RecordChangedEventArgs`1.MaterializeEntity(List`1 messages, IModelToTableMapper`1 mapper)
   at TableDependency.EventArgs.RecordChangedEventArgs`1..ctor(MessagesBag messagesBag, IModelToTableMapper`1 mapper, IEnumerable`1 userInterestedColumns, String server, String database, String sender, CultureInfo cultureInfo)
   at TableDependency.SqlClient.EventArgs.SqlRecordChangedEventArgs`1..ctor(MessagesBag messagesBag, IModelToTableMapper`1 mapper, IEnumerable`1 userInterestedColumns, String server, String database, String sender, CultureInfo cultureInfo)
   at TableDependency.SqlClient.SqlTableDependency`1.GetRecordChangedEventArgs(MessagesBag messagesBag)
   at TableDependency.TableDependency`1.NotifyListenersAboutChange(Delegate[] changeSubscribedList, MessagesBag messagesBag)
   at TableDependency.SqlClient.SqlTableDependency`1.<WaitForNotifications>d__64.MoveNext()

**Comment by christiandelbianco** [comment]
Ah...now i understand. In any case, your C# model can define properties with SET and GET too.

**Comment by georgegeo** [comment]
Ok thank you for all the help!

**Comment by christiandelbianco** [comment]
no problem....Enjoy !
