### ISSUE TITLE
SqlTableDependency does not work once the connection was lost

### ISSUE THREAD

**Issue by Talpidae1** [christiandelbianco/monitor-table-change-with-sqltabledependency#94]
When the database connection is lost and found again after 5 minutes, SqlTableDependency does continue to run on it's own. Is this intended or am I doing anything wrong?
Is there a recommended way to deal with this problem (instead of restarting the application)?

When the connection is lost I get the following exception:
EXCEPTION:
AggregateException
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TableDependency.SqlClient.Extensions.TaskExtensions.<WithCancellation>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TableDependency.SqlClient.SqlTableDependency`1.<WaitForNotifications>d__63.MoveNext()

INNER EXCEPTION:
SqlException
A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The semaphore timeout period has expired.)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

INNER EXCEPTION:
Win32Exception
The semaphore timeout period has expired

-----
This results in: 'TableDependency stopped working' and the status 'StopDueToError'
(We are still using 6.1.0)

**Comment by christiandelbianco** [comment]
Hi. When a database connection is lost, it is normal that an exception is thrown. There is no issue.

Also, SqlTableDependency does NOT continue to run on it's own: any activity is stopped.

**Comment by mrnr1** [comment]
Chris,

Sorry for replying to a closed ticket. Just to confirm, are you stating that there is no way to gracefully handle a loss of connectivity with the database? We occasionally have to restart the MSSQLSERVER service, which in turn kills the connection to our service.

**Comment by christiandelbianco** [comment]
Hi.
what do you mean "gracefully handle a loss of connectivity with the database"?
